// ─── Shared ───────────────────────────────────────────────────────────────────

export interface LineItem {
  id: string;
  itemName: string;
  description: string;
  quantity: number;
  unitPrice: number;
  taxRate: number;
  amount: number;
  discount?: number;
  discountType?: "%" | "flat";
}

// ─── Sales ────────────────────────────────────────────────────────────────────

export interface Customer {
  id: string;
  createdAt: number;
  name: string;
  companyName?: string;
  email: string;
  phone: string;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
  taxId?: string;
  openingBalance?: number;
  /** undefined or true = active; false = deactivated (soft-delete) */
  isActive?: boolean;
}

export interface Quote {
  id: string;
  createdAt: number;
  updatedAt: number;
  quoteNumber: string;
  customerId: string;
  customerName: string;
  date: number;
  /** Kept for backwards-compat; UI treats this as the expiry date */
  dueDate: number;
  expiryDate?: number;
  lineItems: LineItem[];
  subtotal: number;
  taxAmount: number;
  discount?: number;
  total: number;
  notes?: string;
  terms?: string;
  status: "draft" | "sent" | "accepted" | "declined" | "expired" | "invoiced";
  convertedInvoiceId?: string;
}

export interface Invoice {
  id: string;
  createdAt: number;
  updatedAt: number;
  invoiceNumber: string;
  customerId: string;
  customerName: string;
  date: number;
  dueDate: number;
  terms?: string;
  lineItems: LineItem[];
  subtotal: number;
  taxAmount: number;
  discount?: number;
  total: number;
  balance_due: number;
  posted: boolean;
  sent_at?: number | null;
  /** JE id created when the invoice was sent (posted). */
  journalEntryId?: string;
  /** JE id created when the invoice was voided (reversal). */
  voidJournalEntryId?: string;
  notes?: string;
  status: "draft" | "sent" | "partially_paid" | "paid" | "void";
  /** Set when created from a Quote */
  sourceQuoteId?: string;
  /** Set when auto-generated by a RecurringInvoice profile */
  recurringProfileId?: string;
}

export interface InvoicePayment {
  id: string;
  createdAt: number;
  invoiceId: string;
  amount: number;
  paidAt: number;
  method: "cash" | "bank_transfer" | "credit_card" | "check" | "other";
  note?: string;
}

export interface PaymentApplication {
  invoiceId: string;
  invoiceNumber: string;
  amountApplied: number;
}

export interface PaymentReceived {
  id: string;
  createdAt: number;
  paymentNumber: string;
  customerId: string;
  customerName: string;
  date: number;
  amount: number;
  paymentMode: "Cash" | "Bank Transfer" | "Credit Card" | "Check" | "Other";
  referenceNumber?: string;
  notes?: string;
  /** Per-invoice allocation (new model) */
  applications?: PaymentApplication[];
  /** Amount left over after allocations → customer credit */
  unusedAmount?: number;
  // Legacy single-invoice fields (backwards-compat)
  invoiceId?: string;
  invoiceNumber?: string;
}

export interface SalesReceipt {
  id: string;
  createdAt: number;
  receiptNumber: string;
  /** Optional — walk-in / cash sales may not have a customer */
  customerId?: string;
  customerName?: string;
  date: number;
  lineItems: LineItem[];
  subtotal: number;
  taxAmount: number;
  discount?: number;
  total: number;
  paymentMode: "Cash" | "Bank Transfer" | "Credit Card" | "Check";
  status: "completed" | "draft" | "refunded" | "void";
  notes?: string;
}

export interface CreditApplication {
  invoiceId: string;
  invoiceNumber: string;
  amountApplied: number;
  appliedAt: number;
}

export interface CreditNote {
  id: string;
  createdAt: number;
  creditNoteNumber: string;
  customerId: string;
  customerName: string;
  date: number;
  lineItems: LineItem[];
  subtotal: number;
  taxAmount: number;
  total: number;
  /** Original invoice this credit is for (optional) */
  sourceInvoiceId?: string;
  reason?: string;
  notes?: string;
  applications?: CreditApplication[];
  refundedAmount?: number;
  /** Remaining usable credit = total − applied − refunded */
  creditRemaining?: number;
  status: "open" | "closed" | "void";
}

export interface RecurringInvoice {
  id: string;
  createdAt: number;
  profileName?: string;
  customerId: string;
  customerName: string;
  frequency: "daily" | "weekly" | "monthly" | "yearly";
  startDate?: number;
  endDate?: number;
  repeatCount?: number;
  nextInvoiceDate: number;
  lineItems: LineItem[];
  subtotal: number;
  taxAmount: number;
  discount?: number;
  total: number;
  status: "active" | "paused" | "stopped";
  generatedInvoiceIds?: string[];
}

// ─── Purchases ────────────────────────────────────────────────────────────────

export interface Vendor {
  id: string;
  createdAt: number;
  name: string;
  email: string;
  phone: string;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
  taxId?: string;
}

export interface Bill {
  id: string;
  createdAt: number;
  updatedAt: number;
  billNumber: string;
  vendorId: string;
  vendorName: string;
  date: number;
  dueDate: number;
  lineItems: LineItem[];
  subtotal: number;
  taxAmount: number;
  total: number;
  notes?: string;
  status: "draft" | "received" | "approved" | "paid" | "overdue";
}

export interface PaymentMade {
  id: string;
  createdAt: number;
  paymentNumber: string;
  vendorId: string;
  vendorName: string;
  billId?: string;
  billNumber?: string;
  amount: number;
  date: number;
  paymentMode: "Cash" | "Bank Transfer" | "Credit Card" | "Check";
  referenceNumber?: string;
}

export interface VendorCredit {
  id: string;
  createdAt: number;
  creditNumber: string;
  vendorId: string;
  vendorName: string;
  date: number;
  lineItems: LineItem[];
  subtotal: number;
  taxAmount: number;
  total: number;
  status: "open" | "closed";
}

export interface PurchaseOrder {
  id: string;
  createdAt: number;
  updatedAt: number;
  poNumber: string;
  vendorId: string;
  vendorName: string;
  date: number;
  deliveryDate?: number;
  lineItems: LineItem[];
  subtotal: number;
  taxAmount: number;
  total: number;
  notes?: string;
  status: "draft" | "issued" | "billed" | "closed";
}

// ─── Misc / Legacy ────────────────────────────────────────────────────────────

export interface Payment {
  id: string;
  createdAt: number;
}

export interface Expense {
  id: string;
  createdAt: number;
  expenseNumber: string;
  category: string;
  amount: number;
  date: number;
  paymentAccount: string;
  vendorName?: string;
  description?: string;
  billable: boolean;
  status: "unbilled" | "invoiced" | "reimbursed";
}

export interface SalesOrder {
  id: string;
  createdAt: number;
  updatedAt: number;
  orderNumber: string;
}

// ─── Banking ──────────────────────────────────────────────────────────────────

export interface BankAccount {
  id: string;
  createdAt: number;
  accountName: string;
  accountType: "Checking" | "Savings" | "Credit Card";
  accountNumber: string;
  bankName: string;
  balance: number;
}

export interface BankTransaction {
  id: string;
  createdAt: number;
  date: number;
  description: string;
  amount: number;
  type: "deposit" | "withdrawal";
  status: "uncategorized" | "categorized" | "matched";
  category?: string;
  matchedDocumentId?: string;
  matchedDocumentType?: "Invoice" | "Bill" | "Payment";
}

// ─── Accounting ───────────────────────────────────────────────────────────────

export interface JournalLine {
  id: string;
  accountId: string;
  accountName: string;
  description?: string;
  debit: number;
  credit: number;
}

export interface JournalEntry {
  id: string;
  createdAt: number;
  journalNumber: string;
  date: number;
  reference?: string;
  notes: string;
  lines: JournalLine[];
  totalDebit: number;
  totalCredit: number;
  /** "invoice" | "invoice_void" | "manual" — system-generated entries have a source. */
  sourceType?: "invoice" | "invoice_void" | "manual";
  sourceId?: string;
}

export interface COAAccount {
  id: string;
  accountName: string;
  accountType: "Asset" | "Liability" | "Equity" | "Revenue" | "Expense";
  code: string;
  description?: string;
}

export interface Budget {
  id: string;
  createdAt: number;
  year: number;
  budgetName: string;
  entries: { accountId: string; accountName: string; budgetedAmount: number }[];
}

export interface FixedAsset {
  id: string;
  createdAt: number;
  assetName: string;
  assetCode: string;
  purchaseDate: number;
  purchaseValue: number;
  depreciationMethod: "Straight Line" | "Declining Balance";
  rate: number;
  bookValue: number;
}

// ─── Inventory ────────────────────────────────────────────────────────────────

export interface InventoryItem {
  id: string;
  createdAt: number;
  name: string;
  sku: string;
  unit: string;
  salesPrice: number;
  purchasePrice: number;
  stockOnHand: number;
  description?: string;
  type?: "goods" | "service";
  imageUrl?: string;
  isSellable?: boolean;
  salesAccount?: string;
  salesDescription?: string;
  salesTax?: string;
  isPurchasable?: boolean;
  purchaseAccount?: string;
  purchaseDescription?: string;
  purchaseTax?: string;
  preferredVendor?: string;
  trackInventory?: boolean;
  inventoryAccount?: string;
}

export interface PriceList {
  id: string;
  createdAt: number;
  name: string;
  description?: string;
  percentageChange: number;
  type: "markup" | "discount";
}

export interface InventoryAdjustment {
  id: string;
  createdAt: number;
  adjustmentNumber: string;
  itemId: string;
  itemName: string;
  date: number;
  type: "Quantity" | "Value";
  adjustedValue: number;
  reason: "Damage" | "Theft" | "Reconciliation" | "Stock Write-off";
  notes?: string;
}

// ─── Projects ─────────────────────────────────────────────────────────────────

export interface Project {
  id: string;
  createdAt: number;
  projectName: string;
  billingMethod: "Fixed Cost" | "Hourly Rate";
  customerId: string;
  customerName: string;
  rate?: number;
  budget?: number;
  status: "active" | "completed" | "on hold";
}

export interface Timesheet {
  id: string;
  createdAt: number;
  projectId: string;
  projectName: string;
  employeeName: string;
  date: number;
  hours: number;
  billable: boolean;
  description?: string;
}

// ─── Settings ─────────────────────────────────────────────────────────────────

export interface OrgSettings {
  companyName: string;
  fiscalYear: string;
  currency: string;
  taxRate: number;
  logoUrl?: string;
}
